# Generated by Django 4.2.1 on 2023-05-18 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('AD', 'App & Web Development'), ('DM', 'Digital Marketing'), ('GD', 'Graphics Designing'), ('PY', 'Python'), ('AI', 'Artificial Intelligence'), ('GE', 'Government Exams'), ('AD1', 'App & Web Development1'), ('DM1', 'Digital Marketing1'), ('GD1', 'Graphics Designing1'), ('PY1', 'Python1'), ('AI1', 'Artificial Intelligence1'), ('GE1', 'Government Exams1')], max_length=3)),
                ('course_image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
