# Generated by Django 4.2.1 on 2023-05-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course1_subcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcourse',
            name='course',
        ),
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(default='default_image.jpg', upload_to='author_images'),
        ),
        migrations.DeleteModel(
            name='Course1',
        ),
        migrations.DeleteModel(
            name='Subcourse',
        ),
    ]
