# Generated by Django 4.2.1 on 2023-05-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_subcourse_course_author_author_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
