# Generated by Django 4.2.1 on 2023-05-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default_book_image.jpg', upload_to='book_images/'),
        ),
    ]
