# Generated by Django 4.2.1 on 2023-05-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='allCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('book_image', models.ImageField(default='default_image.jpg', upload_to='book_images')),
            ],
        ),
        migrations.CreateModel(
            name='subCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('bookcount', models.BooleanField(default=False)),
                ('popularity', models.IntegerField(default=0)),
                ('image', models.ImageField(default='default_book_image.jpg', upload_to='book_images/')),
                ('featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.allcategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
