# Generated by Django 4.2.1 on 2023-05-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='youtube_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='zoom_link',
            field=models.URLField(blank=True),
        ),
    ]
