# Generated by Django 4.2.1 on 2023-05-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_post_lecture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_lecture',
        ),
    ]
