# Generated by Django 4.2.1 on 2023-05-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcourse',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='subcourse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
