# Generated by Django 4.2.1 on 2023-05-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_cart_cartitem_cart_items_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='subcourse',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
